### ISSUE TITLE
Rerun causes a retrain

### ISSUE THREAD

**Issue by observingClouds** [mllam/mllam-exps#12]
As noted by @matschreiner, rerunning the experiment, e.g. if the evaluation step failed, the training step gets rerun.

~~I assume I know now the root-cause of this.~~ The version.mllam.txt gets rewritten every time and even though its content remains unchanged ~~DVC also checks the mtime. Because the mtime got renewed, the steps depending on version.mllam.txt gets rerun.~~

**Comment by observingClouds** [comment]
A small test shows that the changed mtime is not an issue.

```
stages:
  mllam_version:
    cmd: touch version.mllam.txt
  stage2:
    cmd: echo "Stage 2"
    deps:
      - version.mllam.txt
```
only runs `stage2` during the first pass.
