### ISSUE TITLE
Baseline training configuration

### ISSUE THREAD

**Issue by ealerskans** [mllam/mllam-exps#4]
This is the baseline configuration we discussed today for the `training_params.yaml` file

```yaml
num_workers: 8 
batch_size: 1
hidden_dim: 128
processor_layers: 4
model: hi_lam
graph: hierarchical
epochs: 30
ar_steps_train: 1
lr: 0.001
val_interval: 1
ar_steps_eval: 4
val_steps_to_log: 1 2 4
metrics_watch: val_rmse, mse, random_metric
logger: mlflow
num_nodes: 2
```

This requires an update of `train_wrapper.py` since there has been an addition of variables.

Since we dicussed about using the hierarchical graph instead the graph-creation stage in `dvc.yaml` also needs to be updated:
https://github.com/mllam/mllam-exps/blob/8f940d676ba2e2565ff94e39eccd146905f17b95/dvc.yaml#L10-L12

We discussed about using a hierarchical graph of 4 levels so not sure if that would be something like this
```yaml
  create_graph:
    cmd: python -m neural_lam.create_graph --config_path data/config.yaml --hierarchical --name hierarch_4lev
      --levels 4
```
In the config above named the new graph "hierarch_4lev" but we could perhaps use something more descriptive. @leifdenby I saw that you had a suggestion for this.

The `evaluate_params.yaml` would also need to be updated accordingly.

The slurm training script would also need to be modified since we agreed upon using 2 nodes instead of 1 and currently the number of nodes supplied to the training wrapper is hard-coded to 1, as well as the numebr of nodes to use in the slurm header.
